### ISSUE TITLE
Types for typescript

### ISSUE THREAD

**Issue by Weffe** [Prasanna-sr/express-routes-versioning#7]
Hello,

I am currently in the process of adding types for this package over at the DefinetlyTyped repo. Just figured I would give a heads up. That way anybody looking for types can do so via `npm install @types/express-routes-versioning`

The PR to add the types is here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30419

**Comment by Prasanna-sr** [comment]
sounds good. @Weffe let me know if there are any issues.
